services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    container_name: keycloak
    ports:
      - "9090:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_HTTP_RELATIVE_PATH: /
      KC_PROXY: passthrough
      KC_CORS: true
      KC_CORS_ALLOWED_ORIGINS: http://localhost:8080/*
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/import/realm-export.json:/opt/keycloak/data/import/realm-export.json

  swagger-editor:
    image: docker.swagger.io/swaggerapi/swagger-editor
    container_name: swagger-editor
    ports:
      - "8081:8080"
    volumes:
      - ./swagger-editor:/tmp
    environment:
      SWAGGER_FILE: /tmp/api/openapi.yaml
